/* eslint-disable */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import { a } from "@aws-amplify/data-schema";
import { configure } from "@aws-amplify/data-schema/internals";
import { secret } from "@aws-amplify/backend";

export const schema = configure({
    database: {
        identifier: "xxxxxxxxxxxxxxxxxxxxxxxxxx",
        engine: "mysql",
        connectionUri: secret("SQL_CONNECTION_STRING")
    }
}).schema({
    "ticketing": a.model({
        id: a.integer().required(),
        requester_name: a.string().required(),
        requester_email: a.string().required(),
        severity: a.string(),
        reason_for_high: a.string(),
        notes_request: a.string(),
        time_requested: a.datetime(),
        status: a.string(),
        notes_resolution: a.string(),
        time_resolved: a.datetime()
    }).identifier([
        "id"
    ])
});
